# Generated by Django 5.1.6 on 2025-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
